const VAR = "@";

/**
    Document object model for the page
*/
export let DOM = {
    "problemdivid": "lce_problem",
    "headerdivid": "header",
    "bodydivid": "body",
        "titledivid": "title",
        "stepdivid": "step",
        "questiondivid": "question",
            "canvasdivclass": "canvasarea",
            "canvasdivid": "canvasarea--" + VAR + "id" + VAR,
                "canvasclass": "canvas",
                "canvasid": "canvas--" + VAR + "id" + VAR,
                "staticcanvasid": "canvas--static--" + VAR + "id" + VAR,
                "dynamiccanvasid": "canvas--dynamic--" + VAR + "id" + VAR,
                "canvasinfodivclass": "canvasinfo",
                    "canvaspointclass": "canvaspoint",
                    "canvaspointid": "canvaspoint--" + VAR + "id" + VAR,
                    "canvasmodeclass": "canvasmode",
                    "canvasmodeid": "canvasmode--" + VAR + "id" + VAR,
            "textboxdivclass": "textentry",
                "textboxspanclass": "textboxlabel",
                "textboxclass": "textbox",
                "textboxid": "textbox--" + VAR + "id" + VAR,
                "textboxanswerclass": "textboxanswer",
                "textboxanswerid": "textboxanswer--" + VAR + "id" + VAR,
                "textboxanswershown": "textboxanswershown",
            "textspanclass": "textspan",
        "buttonsdivid": "buttons",
            "beginbuttonid": "beginbutton",
            "restartbuttonid": "restartbutton",
                "restartzeroid": "restartzero",
                "restartoneid": "restartone",
                "restartabortid": "restartabort",
            "hintbuttonid": "hintbutton",
            "submitbuttonid": "submitbutton",
            "nextbuttonid": "nextbutton",
            "scorebuttonid": "scorebutton",
            "showgradebuttonid": "showgradebutton",
            "feedbackbuttonid": "feedbackbutton",
        "scoredivid": "scorediv",
            "scoretitleid": "scoretitle",
            "currentquestionid": "currentquestion",
            "lastscorerowid": "lastscorerow",
        "gradedivid": "submitgrade",
            "gradeformid": "gradeform",
            "gradenametextid": "gradenametext",
            "gradecuidtextid": "gradecuidtext",
            "gradecoursetextid": "gradeclasstext",
            "submitgradebuttonid": "submitgradebutton",
            "gradeservererrorid": "gradeservererror",
        "feedbackdivid": "feedback",
            "feedbackformid": "feedbackform",
            "feedbacknametextid": "feedbacknametext",
            "feedbackemailtextid": "feedbackemailtext",
            "feedbackinputtextid": "feedbackinputtext",
            "submitfeedbackbuttonid": "submitfeedbackbutton",
            "feedbackservererrorid": "feedbackservererror",
        "modaldivid": "modaldiv",
            "modalclass": "modal",
            "restartmodal": "restartmodal",
            "gradesubmitmodal": "gradesubmitmodal",
            "feedbackmodal": "feedbackmodal",
    "footerdivid": "footer",
    "hiddentextclass": "hiddentext",
    "hiddenclass": "hidden",
    "disabledclass": "disabled",
    "hidescoreclass": "hidescore",

    "tipboxdivclass" : "tipbox",
    "tipboxdivid" : "tipbox--" + VAR + "id" + VAR,
    "tipboxtextclass" : "tiptext",
    "tipboxcheckid" : "tipcheck--" + VAR + "id" + VAR,
    "tipboxdontshowclass" : "tipdontshow",
    "tipboxbuttonclass" : "tipbutton",
    "tipboxbuttonid" : "tipbutton--" + VAR + "id" + VAR,
}
